import type { MigrationBuilder } from 'node-pg-migrate';

export const shorthands: undefined = undefined;

/**
 * Adds a human-readable sequential identifier to tasks.
 *
 * `id` (uuid) stays the primary key 
 * `task_number` is a separate, DB-managed counter that
 * the UI formats as "TASK-<n>". Stored as a bare BIGINT (no prefix) so it
 * remains sortable and range-queryable.
 *
 * GENERATED BY DEFAULT AS IDENTITY gives us a Postgres-managed sequence:
 * concurrency-safe, monotonically increasing, and unique. We add a UNIQUE
 * constraint as well so the legible ID is guaranteed distinct.
 */
export function up(pgm: MigrationBuilder): void {
  pgm.addColumn('tasks', {
    task_number: {
      type: 'bigint',
      notNull: true,
      sequenceGenerated: {
        precedence: 'BY DEFAULT',
      },
    },
  });

  pgm.addConstraint('tasks', 'tasks_task_number_unique', {
    unique: ['task_number'],
  });
}

export function down(pgm: MigrationBuilder): void {
  pgm.dropConstraint('tasks', 'tasks_task_number_unique');
  pgm.dropColumn('tasks', 'task_number');
}
